### ISSUE TITLE
Change auction fee into ETH, not token

### ISSUE THREAD

**Issue by ruymaster** [IrrigationProtocol/irrigation-contracts-diamond#58]

**Comment by Super-Genius** [comment]
This should be changing auction listing fee into ETH and closing Fee is taken from successful auction fees that the buyer paid in Whitelisted assets for buying (i.e. Stable Coins percentage)

**Comment by ruymaster** [comment]
So, only when listing token on auction market, contract will check holding water, right?

**Comment by Super-Genius** [comment]
Anyway to check the amount of water they continued to store during the auction period?

That way they need to keep it locked/stored or a pro-rata amount to determine the close percentage?

Like if they stored 3200, did the auction then unstored all, the success % would be calculated on the stored average water during the auction period and chose the 0 water lookup in this case.

**Comment by ruymaster** [comment]
Sure, I think that it is possible. There are several transactions like creating, bidding, and buying, on one auction. So, contract can record holding water per each transaction for one auction.

**Comment by ruymaster** [comment]
Currently, didn't implement getting average stored water. It increases gas fee and I think it is better to keep only stored water.
