### ISSUE TITLE
Old selectors are not deleted

### ISSUE THREAD

**Issue by ruymaster** [IrrigationProtocol/irrigation-contracts-diamond#68]
- When upgrading old facet to new facet, the selectors that are not in new facet should be deleted.

**Comment by Super-Genius** [comment]
That's interesting because the typescript scripts in gnus-ai contracts for deployment have this functionality.

**Comment by ruymaster** [comment]
While testing upgrade script, I found some old selectors are not removed on diamond. 
For example, I updated parameters in getAuctionFee function. If I upgrade contract with new getAuctionFee function, old getAuctionFee function selector should be deleted. But it is not deleted.

**Comment by ruymaster** [comment]
Done
